name: starter_project
description: A sample command-line application.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  approval_tests: ^0.4.6

dev_dependencies:
  sizzle_lints: ^2.0.2
  test: ^1.25.5
