name: starter_project
description: A sample command-line application.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ^3.3.4

dependencies:
  approval_tests: 0.4.5

dev_dependencies:
  sizzle_lints: ^2.0.2
  test: ^1.25.5
